### ISSUE TITLE
nanovg displays wrong colours for loaded PNG images

### ISSUE THREAD

**Issue by nek0** [cocreature/nanovg-hs#6]
I encountered a Problem while using nanovg. When I load Images, they get displayed with wring colours or only as white silhouettes of the non-transparent areas. I compiled a minimal example at <https://github.com/nek0/nanovg-minimal-error>. I'm not sure whether this is an Error of the Haskell bindings or of the upstream library.

**Comment by cocreature** [comment]
Not sure what exactly is going on here. I’m tempted to say this is either a bug in `nanovg` itself or a usage error since there is nothing particularly special in the bindings for this. The next step in debugging this would be to try and reproduce it using a simple C/C++ program. I’ll get to that eventually but it will probably take some time so if you want to take a shot at it yourself, go for it!

**Comment by nek0** [comment]
Hi again. With a little help i whipped up a minimal example in C, which has the same display error. You can find it in <https://github.com/nek0/nanovg-minimal-error-c>.

**Comment by nek0** [comment]
after more cyber-entomology we found out, that this is in fact an error from my side. when creating the image pattern, the alpha should be `1` and not `255`. Sorry for bothering you.

**Comment by cocreature** [comment]
No worries, I’m happy you were able to figure it out! 🎉
